### ISSUE TITLE
Three DeprecationWarning on Python 3.7

### ISSUE THREAD

**Issue by jayvdb** [zuo/unittest_expander#1]
```
/usr/lib/python3.7/site-packages/unittest_expander.py:1781: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    collections.Sequence,

/usr/lib/python3.7/site-packages/unittest_expander.py:1782: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    collections.Set,

/usr/lib/python3.7/site-packages/unittest_expander.py:1863: DeprecationWarning: inspect.getargspec() is deprecated since Python 3.0, use inspect.signature() or inspect.getfullargspec()
    arg_spec = inspect.getargspec(base_func)
```

**Comment by jayvdb** [comment]
Note that py38 was released and it didnt break this.  The problem was deferred to py39 ;-)

**Comment by zuo** [comment]
Thanks for your feedback. As far as I know, recently the problem was deferred even to py3.10. :-)

Anyway, I am going to make a new release (though, rather, not soon) -- so then I will include also a correction of this issue.

**Comment by jayvdb** [comment]
Looking forward to the release.

I am using this library in the test suites of https://github.com/jayvdb/https-everywhere-py and https://github.com/jayvdb/pypidb

**Comment by adsharma** [comment]
@zuo: would love to have this in PyPI

**Comment by jayvdb** [comment]
Note Python 3.10.0 is now at b3 , and should be released very soon.  This needs to be released to allow people to run tests on Python 3.10

**Comment by zuo** [comment]
Hello.

@jayvdb @adsharma Big thanks for you contribution!

I apologise for such a long inactivity -- for personal reasons I was unable to actively maintain the project, but now that will change.

**I hope I'll be able to release a new stable version in the coming weeks... It will, of course, include fixes of the problems you pointed out.**

Best regards!

**Comment by adsharma** [comment]
Still looking for this

**Comment by zuo** [comment]
Again, I must apologize for such a long inactivity...

But now the 0.4.0 release, which includes also fixes of these problems, is finally done! :-)
