### ISSUE TITLE
Drop python 2 and get rid of eval

### ISSUE THREAD

**Issue by KOLANICH** [zuo/unittest_expander#10]
The mere presence of packages with `eval` in them in my system makes it less secure: other packages may use functions from your package to circumvent detection of eval usage.

**Comment by jayvdb** [comment]
The [`eval(..)`](https://github.com/zuo/unittest_expander/blob/269b9e875d55e9062ebac1e95bcee00aafc18a86/unittest_expander.py#L2483) is not used on arbitrary code able to be supplied by the caller.

Still, https://github.com/jazzband/contextlib2/tree/v0.6.0.post1 should be used instead. The releases after that are py3.6+ only.

**Comment by KOLANICH** [comment]
>The eval(..) is not used on arbitrary code able to be supplied by the caller.

You are right.
